name: Build and Deploy Hugo Blog

on:
  push:
    branches:
      - main   # 只在 main 分支 push 时触发

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true   # 如果主题是子模块必须加

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.150.0'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}       # 服务器 IP
          username: ${{ secrets.SERVER_USER }}   # 登录用户名（比如 root 或 admin）
          key: ${{ secrets.SERVER_SSH_KEY }}     # 服务器对应的 SSH 私钥
          source: "./public/*"
          target: "/var/www/myblog"              # 服务器上的存放路径
